customer/urls.py
from django import views
from django.urls import path
from . import views

app_name='customer'

urlpatterns = [
    path('',views.index,name='index'),
    path('signup',views.signup,name='signup'),
    path('login',views.login,name='login'),
    path('verifyotp', views.verify_otp, name='verify_otp'),
    path('home',views.customer_home,name='cust_home'),
    path('logout',views.cust_logout,name='logout'),
    path('search', views.search_products, name='search'),
    path('product/<int:id>', views.view_product, name='view_product'),
    path('add-to-bag', views.add_to_bag, name="add_to_bag"),
    path('bag', views.view_bag, name="bag"),
    path('update-qty', views.update_quantity, name="update_qty"),
    path('order-product', views.order_product, name='order_product'),
    path('update-payment', views.update_payment, name='update_payment'),
    path('my-orders', views.view_orders, name='my_orders'),
    path('change-passwd', views.change_password, name='change_passwd'),
    path('profile', views.view_profile, name='profile'),
    path('edit-profile', views.update_profile, name='update_profile'),
    path('password-otp', views.send_otp, name='send_otp'),
    path('forgot-passwd', views.forgot_passwd, name='forgot'),
    path('check_avilable/',views.check_avilable,name="check_available")



]

e_commerce/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ecom/',include('customer.urls')),
    path('ecom-admin/',include('ecom_admin.urls')),
    path('reseller/',include('reseller.urls'))
]+static(settings.MEDIA_URL, document_root =  settings.MEDIA_ROOT)

customer/models.py
import datetime
import imp
from django.db import models
from reseller.models import Products, Resellers
# Create your models here.

class Customer(models.Model):
    first_name = models.CharField(max_length=30,db_column='f_name')
    last_name = models.CharField(max_length=30,db_column='l_name')
    mobile = models.CharField(max_length=12,db_column='mob')
    gender = models.CharField(max_length=6,db_column='gender')
    dob = models.DateField(db_column='dob')
    address = models.CharField(max_length=70,db_column='addr')
    country = models.CharField(max_length=30,db_column='cntry')
    user_type = models.CharField(max_length=10,db_column='u_type')
    email = models.CharField(max_length=50,db_column='email')
    passwd = models.CharField(max_length=50,db_column='passwd')
    otp = models.CharField(max_length=70,db_column='otp')
    status = models.CharField(max_length=20, default="",db_column='status')

    class Meta:
        db_table="customer"


class Orders(models.Model):
    product_id = models.ForeignKey(Products, on_delete=models.CASCADE,db_column='p_id')
    reseller = models.ForeignKey(Resellers, on_delete=models.CASCADE,db_column='reseller',null=True)
    customer_id = models.ForeignKey(Customer, on_delete=models.CASCADE,db_column='c_id')
    order_date = models.DateField(default=datetime.date.today,db_column='ord_date')
    qty = models.IntegerField(db_column='qty')
    status = models.CharField(max_length=30,db_column='status')

    class Meta:
        db_table="orders"

customer/views.py
from random import randint
import razorpay
from tracemalloc import get_traced_memory
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from random import randint
from django.conf import settings
from django.core.mail import send_mail
from django.db.models import Q
from reseller.models import Resellers
# from ..reseller import models
# from e_commerce.reseller.models import Resellers
from django.utils.crypto import get_random_string

from reseller.models import Resellers,Products
from .models import *

# Create your views here.

def index(request):
    return render(request,'customer/index.html')


def signup(request):

    if request.method=='POST':

        user_type=request.POST['user_type']
        
        if user_type=='customer':
            first_name=request.POST['first_name'].lower()
            last_name=request.POST['last_name'].lower()
            gender=request.POST['gender']
            dob=request.POST['dob']
            addr=request.POST['addr']
            country=request.POST['country']
            mobile=request.POST['mobile']
            email=request.POST['email']
            password=request.POST['password']
            
            customer_exist=Customer.objects.filter(email=email).exists()

            if not customer_exist:
                otp = randint(1000, 9999)
                send_mail(
                    'please verify your otp',
                    str(otp),
                    settings.EMAIL_HOST_USER,
                    [email],
                    
                )
                customer_data=Customer(first_name=first_name,last_name=last_name,gender=gender,
                user_type=user_type,email=email,dob=dob,address=addr,country=country,mobile=mobile,passwd=password,status='otpverify', otp=str(otp))
                customer_data.save()
                customer=Customer.objects.get(email=email)
                request.session['cust_id']=customer.id
                return redirect('customer:verify_otp')

        if user_type=='reseller':

            cmp_name=request.POST['cmp_name']
            cmp_reg=request.POST['cmp_reg']
            cmp_addr=request.POST['addr']
            country=request.POST['country']
            mobile=request.POST['mobile']
            email=request.POST['email']
            acc_holder=request.POST['acc_name']
            acc_no=request.POST['acc_no']
            acc_ifsc=request.POST['acc_ifsc']
            password=request.POST['password']
            log_id=randint(1000, 9999)

            reseller_exist=Resellers.objects.filter(email=email).exists()

            if not reseller_exist:
                reseller=Resellers(cmp_name=cmp_name,company_regid=cmp_reg,cmp_addr=cmp_addr,
                country=country,cmp_phno=mobile,acc_no=acc_no,acc_holder=acc_holder,acc_ifsc=acc_ifsc,user_type=user_type,
                email=email,user_id=log_id,passwd=password)

                reseller.save()
                subject='You Login ID is '+str(log_id)
                send_mail(
                    'login credentials',
                    subject,
                    settings.EMAIL_HOST_USER,
                    [email],
                    
                )
                msg='Registration Successfull'
            else:
                msg='Email Exist'   
            return render(request,'customer/signup.html',{'msg':msg})

    return render(request,'customer/signup.html')

def login(request):

    if request.method=='POST':
        
        user_name=request.POST['user_name']
        passwd=request.POST['passwd']
       
        if '@' in user_name:
            customer_exist=Customer.objects.filter(email=user_name,passwd=passwd).exists()
            print(customer_exist)
            if customer_exist:
                
                customer=Customer.objects.get(email=user_name,passwd=passwd)
                request.session['cust_id']=customer.id
                if customer.status=='otpverify':
                   
                    otp = randint(1000, 9999)
                    send_mail(
                        'please verify your otp',
                        str(otp),
                        settings.EMAIL_HOST_USER,
                        [customer.email],
                        fail_silently=False,
                    )
                    customer.otp=otp
                    customer.save()
                    return redirect('customer:verify_otp')
                return redirect('customer:cust_home')
            else:
                return render(request, 'customer/login.html', {'error': 'Invalid user details'})
                
        elif user_name.isdigit():

            seller_exist=Resellers.objects.filter(user_id=user_name,passwd=passwd).exists()
            
            if seller_exist:
                seller_data=Resellers.objects.get(user_id=user_name,passwd=passwd)
               
                if seller_data.status=='active':
                    
                    request.session['s_id']=seller_data.id
                    return redirect('reseller:reseller_home')
                
                else: 
                    return render(request, 'customer/login.html', {'error': 'Account Not Approved Yet'})
            
            else:
                    return render(request, 'customer/login.html', {'error': 'UserName Or Password Incorrect'})
    return render(request,'customer/login.html')

def verify_otp(request):
    
    if request.method=='POST':

        otp = request.POST['inp_otp']
        c_id=request.session['cust_id']
        data=Customer.objects.get(id=c_id)
       
        if otp==data.otp:
            Customer.objects.filter(id=c_id).update(status='active')
            return redirect('customer:cust_home')
        else:
            return render(request, "customer/verify_otp.html", {"msg": "Invalid otp"})
    return render(request,'customer/verify_otp.html')

def customer_home(request):
    return render(request,'customer/home.html')

def search_products(request):
    # search data based on keyword
    if request.method == "POST":
        search_word = request.POST['searchdata']
        # search_list=search_word.split(' ')
        print(search_word)
        srch_products=Products.objects.filter(Q(vendor__icontains=search_word)|Q(title__icontains=search_word)| Q(category__icontains=search_word)|Q(subcategory__icontains=search_word),status='active' )

      
        print(srch_products)
        # Rendering search product page
        return render(request, "customer/search_products.html",{"search_products":srch_products})
    else:
        return redirect('customer:index')


def view_product(request,id):
    product = Products.objects.get(id=id)
    return render(request, "customer/view_product.html",{ 'product': product, })


def add_to_bag(request):

    prod_id=Products.objects.get(id=request.POST['id'])
    reseller_id=Resellers.objects.get(id=prod_id.reseller.id)
    quantity=request.POST['quantity']
    cust_id=Customer.objects.get(id=request.session['cust_id'])
    data_exist=Orders.objects.filter(customer_id=request.session['cust_id'],product_id=prod_id)
    if not data_exist:
        order_data=Orders(product_id=prod_id,qty=quantity,customer_id=cust_id,status='added_to_bag',reseller=reseller_id    )
        order_data.save()
        return JsonResponse({"status": "success"})
    else:
        return JsonResponse({"status": "error"})


def cust_logout(request):
    if 'cust_id' in request.session:
        del request.session['cust_id']
        request.session.flush()
    return redirect('customer:cust_home')


def view_bag(request):
    total=0
    if request.method == 'POST':
        pass
        # cust_id = request.session['cust_id']
        # bagdata = Orders.objects.filter(customerid=cust_id, status='added_to_bag')
        # bag_ids = bagdata.values_list('product_id_id')
        # productdata = Products.objects.filter(id__in=bag_ids)
        # bgdata=[{'email': usr.email, 'joindate': usr.date_joined} for bg in bgdata]
    else:
        cust_id = request.session['cust_id']
        bag_data = Orders.objects.filter(customer_id=cust_id, status='added_to_bag')
        # bag_ids = bag_data.values_list('product_id_id')
        # products = Products.objects.filter(id__in=bag_ids)
        # price = 0
        # for prod in products:
        #     for bg in bag_data:
        #         if bg.product_id_id == prod.id:
        #             price = price + (bg.qty * prod.price)
        # print(price)

        for prod in bag_data:
            price=prod.product_id.price*prod.qty
            total+=price

        return render(request,"customer/view_bag.html",{'bag_data': bag_data,  'total': total})


def update_quantity(request):

    total=0
    qty=request.GET['qty']
    order_id=request.GET['ord_id']
    order_detail=Orders.objects.get(id=order_id)
    order_detail.qty=qty
    
    order_detail.save()
    product_total=order_detail.product_id.price* int(qty)
    bag_data = Orders.objects.filter(customer_id=request.session['cust_id'],status='added_to_bag')
    for prod in bag_data:
            price=prod.product_id.price*prod.qty
            total+=price
   
    print('***********',product_total)
    return JsonResponse({"total": total,"product_total":product_total})


def order_product(request):

    order_amount = request.POST['total']
    order_currency = 'INR'
    order_receipt = 'order_rcptid_11'
    notes = {'Shipping address': 'Bommanahalli, Bangalore'}
    type(order_amount)
    client = razorpay.Client(auth=('rzp_test_jznmHCFBf6ZMUd','hMGwzenl3b1QwDmJxDtyAUNy'))
    payment = client.order.create({"amount": order_amount, "currency": order_currency, "receipt": order_receipt, 'notes': notes})
    return JsonResponse( payment)


def update_payment(request):

    print('reached here')
    Orders.objects.filter(customer_id=request.session['cust_id'], status='added_to_bag').update(status='paid')
    return JsonResponse({'resp': "success"})

customer/templates/customer/change_password.html
{% extends "customer/cust_master.html" %} {% load static %} {% block content %}

<div class="container-fluid login-container">
    <div class="row">
        <div class="col-lg-4 col-md-3 col-sm-2"></div>
        <div class="col-lg-4 col-md-6 col-sm-8">
            <div class="form-login">
                <br>
                <h3 class="login-head">Change password</h3><br>
                <p style="color: green;" id="stats">{{ msg }}</p>
              
                <form method="POST" action="">
                    {% csrf_token %}
                    <div id="pass_section">
                        <input type="text" id="OTP" name="otp" class="form-control input-sm chat-input" placeholder="Enter your OTP" />
                        <br>
                        <input type="password" id="userpassword" name="password" class="form-control input-sm chat-input" placeholder="password" /><br>
                        <input type="password" id="cnfpass" name="cnfPassword" class="form-control input-sm chat-input" placeholder="Confirm password" />
                        <span class="group-btn"><br>
                            <button class="btn btn-md" type="button" style="background-color: #00796b; color: white;" onclick="changepass()">
                                Change password
                            </button>
                        </span>
                    </div>

                </form>
            </div>

        </div>
        <div class="col-lg-4 col-md-3 col-sm-2"></div>
    </div>
</div>
<script src="{% static 'reseller/scripts/jquery-3.5.1.min.js' %}"></script>
<script>
    function changepass() {
        otp = document.getElementById("OTP");
        pass = document.getElementById("userpassword");
        cnfpass = document.getElementById("cnfpass");
        var x = 0;
        if (pass.value !== cnfpass.value) {
            pass.style.borderColor = "#FF0000";
            cnfpass.style.borderColor = "#FF0000";
            // document.getElementById('stats').style.color = "red";
            // document.getElementById('stats').innerHTML = "password and confirm password missmatch";
            x = 1;
        } else {
            pass.style.borderColor = "#ced4da";
            cnfpass.style.borderColor = "#ced4da";
        }
        if (pass.value == "") {
            // document.getElementById('stats').style.color = "red";
            pass.style.borderColor = "#FF0000";
            // document.getElementById('stats').innerHTML = "Invalid password";
            x = 1;
        }
        if (otp.value.length < 4) {
            otp.style.borderColor = "#FF0000";
             document.getElementById('stats').style.color = "red";
             document.getElementById('stats').innerHTML = "Invalid OTP";
            x = 1;
        } else {
            otp.style.borderColor = "#ced4da";
        }
        console.log("normal")
        if (x == 1) {
            console.log("test")
        } else {
            console.log("success")
            $.ajaxSetup({
                headers: {
                  "X-CSRFToken": $('[name=csrfmiddlewaretoken]').val()
                }
            })
            $.ajax({
                url: 'http://127.0.0.1:8000/ecom/change-passwd',
                type: 'POST',
                data: {
                    password: $('#userpassword').val(),
                    otp: $('#OTP').val(),
                },
                success: function(response) {
                    if (response.status == 'success') {
                        alert("Your password changed successfully")
                        window.location.href = "http://127.0.0.1:8000/ecom/home"
                    } else {
                        document.getElementById('stats').style.color = "red";
                        document.getElementById('stats').innerHTML = response.res;
                    }
                }
            })
        }
    }
</script>
{% endblock %}
<!-- 
</body>

</html> -->

customer/templates/customer/cust_master.html
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="{% static 'ecom/scripts/validate.js' %}"></script>
    <link rel="stylesheet" href="{% static 'ecom/css/style-home.css' %}">
    <link rel="stylesheet" href="{% static 'ecom/css/customer-style.css'%}">


    <link rel="stylesheet" href="{% static 'ecom/css/style-home.css' %}">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="{% static 'ecom/scripts/jquery-3.5.1.min.js' %}"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light navigation fixed-top">
        <div class="mx-2 my-auto">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
            <img src="{% static 'ecom/images/cybersquare-logo.png' %} " alt=" " class="logo-nav">
        </div>
        <div class="collapse d-inline  navbar-collapse" id="navbarSupportedContent">
            <form class="mx-2 my-auto d-inline w-100" action="{% url 'customer:search' %}" method="POST">
                {% csrf_token %}
                <div class="input-group">
                    <input type="text" name="searchdata" id="serch" class="form-control border border-right-0" placeholder="Search...">
                    <span class="input-group-append">
                    <button class="btn btn-secondary border border-left-0 searh-btn" type="submit" id="srch">
                        <i class="fa fa-search "></i>
                    </button>
                    </span>
                </div>
            </form>
            <ul class="navbar-nav mr-auto " style="margin-left: 30px;">
                {% if 'cust_id' in request.session %}
                <div class="btn-group">
                    <button type="button" style="background-color: transparent;" class="btn bg_none dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <h2 class="fas fa-user-cog"></h2>
                    </button>
                    <div class="dropdown-menu dropdown-menu-right">
                        <a class="dropdown-item" href="{% url 'customer:profile' %}" type="button">Profile</a>
                        <a class="dropdown-item" type="button" href="{% url 'customer:bag' %}">View Bag</a>
                        <a class="dropdown-item" type="button" href="{% url 'customer:my_orders' %}">My orders</a>
                        <a class="dropdown-item" href="{% url 'customer:send_otp' %}" type="button">Change password</a>
                        <a class="dropdown-item" href="{% url 'customer:logout' %}" type="button">Logout <i class="fa fa-sign-out" aria-hidden="true"></i></a>
                    </div>
                </div>
                {% else %}
                <div class="login-nav">
                    <button onclick="location.href = '/ecom/login'" type="button" class="btn">Login</button>
                </div>
                {% endif %}

            </ul>
        </div>
    </nav>
    <nav class=" navbar navbar-expand-lg nav-list rounded-bottom" style="margin-top: 75px;">
        <ul class="navbar-nav">
            <div class="dropdown drpdown">
                <li class="dropbtn">Electronics </li>
                <div class="dropdown-content drpdown-content">
                    <a href="#" class="btn">Mobile & accessories</a>
                    <a href="#" class="btn">Laptop</a>
                    <a href="#" class="btn">Speaker</a>
                    <a href="#" class="btn">Camera</a>
                    <a href="#" class="btn">Gaming & Accessories</a>
                </div>
            </div>
            <div class="dropdown drpdown">
                <li class="dropbtn">TV & appliances </li>
                <div class="dropdown-content drpdown-content">
                    <li><a href="#" class="btn">Television</a></li>
                    <li><a href="#" class="btn">Refrigerators</a></li>
                    <li><a href="#" class="btn">Washing Machine</a></li>
                    <li><a href="#" class="btn">Kitchen Appliances</a></li>
                </div>
            </div>
            <div class="dropdown drpdown">
                <li class="dropbtn">Sports </li>
                <div class="dropdown-content drpdown-content">
                    <li><a href="#" class="btn">Football</a></li>
                    <li><a href="#" class="btn">Cricket</a></li>
                    <li><a href="#" class="btn">Tennis</a></li>
                </div>
            </div>
            <div class="dropdown drpdown">
                <li class="dropbtn">Fashion </li>
                <div class="dropdown-content drpdown-content">
                    <li><a href="#" class="btn">Mens</a></li>
                    <li><a href="#" class="btn">Womens</a></li>
                    <li><a href="#" class="btn">kids</a></li>
                </div>
            </div>
        </ul>
    </nav>
    <div style="min-height:400px">
        {% block content %}
        {% endblock %}
    </div>
  
    <!-- Navigation bar ends here -->
    <footer class="foot text-center text-lg-start" style="background-color: #e0f2f1;">
        <div class="container p-4">
            <div class="row">
                <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
                    <h5 class="text-uppercase">Registred office address</h5>
                    <p>
                        5th Floor, CAFIT Square, Hilite Business Park, Thondayad Bye-Pass Thondayad, Hilite City, Poovangal, Kozhikode, Kerala 673016
                    </p>
                </div>
                <div class="col-lg-2 col-md-4 mb-4 mb-md-0" style="text-align: left;">
                    <h5 class="text-uppercase">POLICY</h5>
                    <ul class="list-unstyled mb-0">
                        <li><a href="#!" class="text-dark">Return Policy</a></li>
                        <li><a href="#!" class="text-dark">Terms of use</a></li>
                        <li><a href="#!" class="text-dark">Security</a></li>
                        <li><a href="#!" class="text-dark">Privacy</a></li>
                    </ul>
                </div>
                <div class="col-lg-2 col-md-4 mb-4 mb-md-0" style="text-align: left;">
                    <h5 class="text-uppercase mb-0">About</h5>
                    <ul class="list-unstyled">
                        <li><a href="#!" class="text-dark">Contact Us</a></li>
                        <li><a href="#!" class="text-dark">About Us</a></li>
                        <li><a href="#!" class="text-dark">Careers</a></li>
                        <li><a href="#!" class="text-dark">Cybersquare Wholesale</a></li>
                    </ul>
                </div>
                <div class="col-lg-2 col-md-4 mb-4 mb-md-0" style="text-align: left;">
                    <h5 class="text-uppercase mb-0">Social</h5>
                    <ul class="list-unstyled">
                        <li><a href="#!" class="text-dark">Facebook</a></li>
                        <li><a href="#!" class="text-dark">Twitter</a></li>
                        <li><a href="#!" class="text-dark">Youtube</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
            <img src="{% static 'ecom/images/cards.png' %}" class="img-fluid w-25" alt="">
        </div>
    </footer>

</body>

</html>

customer/templates/customer/login.html
{% extends "customer/cust_master.html" %} {% load static %} {% block content %}

<div class="container-fluid login-container">
    <div class="row">
        <div class="col-lg-4 col-md-3 col-sm-2"></div>
        <div class="col-lg-4 col-md-6 col-sm-8">
            <div class="form-login">
                <br>
                <h3 class="login-head">Login</h3><br>
                <p style="color: red;">{{ error }}</p>
                <form action="{% url 'customer:login' %}" method="POST">
                    {% csrf_token %}
                    <input type="text" id="username" name="user_name" class="form-control input-sm chat-input" placeholder="username" />
                    </br>
                    <input type="password" id="userpassword" name="passwd" class="form-control input-sm chat-input" placeholder="password" />
                    </br>
                    <div class="wrapper">
                        <span class="group-btn">
      
                            <!-- <a href="#" class="btn btn-light btn-md">login <i class="fa fa-sign-in"></i></a> -->
                            <button class="btn btn-md" type="submit" style="background-color: #00796b; color: white;" onclick="return validate_login()">
                                login <i class="fa fa-sign-in"></i>
                            </button>
                        </span><br>
                        <span>
                            <br>
                            <a href="/ecom/changepassword"><label for="" class="">Forgot password?</label></a><br>
                            <a href="{% url 'customer:signup' %}"><label for="" class="">Create an account?</label></a>
                        </span>
                    </div>
                </form>
            </div>

        </div>
        <div class="col-lg-4 col-md-3 col-sm-2"></div>
    </div>
</div>
{% endblock %}
<!-- 
</body>

</html> -->

customer/templates/customer/view_orders.html
{% extends "customer/cust_master.html" %} {% block content %}{% load static %}
<!--  -->
{% if bag_data %}
<div class="container">
    <div class="row" style="min-height: 300px;">
        <h2 class="mt-2 mb-2">My Orders</h2>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Image</th>
                    <th scope="col">Product Name</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Order Date</th>
                    <th scope="col">Total Price</th>
                </tr>
            </thead>
            <tbody>
                {% for order in bag_data %}
                <tr>
                    <!-- <td></td> -->

                    {% comment %} {% for product in product_data %} {% if order.product_id_id == product.id %}
                    <td><img src="/media/{{ product.img }}" alt="" srcset="" height="100px" width="100px"></td>
                    <td>{{ product.title }}</td>
                    <td>
                        <input type="number" onchange="update_quantity(this,'{{order.id}}','{{ product.price }}','price{{ forloop.parentloop.counter }}')" value="{{ order.quantity }}" min="1" max="99" style="width: 40px;">
                    </td>
                    <td><span>&#8377;</span><input type="number" id="price{{ forloop.parentloop.counter }}" value="{{ product.price }}" min="1" readonly></td>
                    {% endif %}{% endfor %}
                </tr>
                {% endfor %} {% endcomment %}
                {% comment %} {% for product in product_data %} {% if order.product_id_id == product.id %} {% endcomment %}
                <td><img src="{{order.product_id.img.url }}" alt="" srcset="" height="100px" width="100px"></td>
                <td>{{ order.product_id.title|title }}</td>
                <td>
                    {% comment %} <input type="number" onchange="update_quantity(this,'{{order.id}}','{{ product.price }}','price{{ forloop.parentloop.counter }}')" value="{{ order.qty }}" min="1" max="99" style="width: 40px;"> {% endcomment %}
                    {% comment %} <input type="number" readonly value="{{ order.qty }}" min="1" max="99" style="width: 40px;"> {% endcomment %}
               {{order.qty}} No{{order.qty|pluralize}} 
                </td>
                <td>
                    {% comment %} <input type="number" onchange="update_quantity(this,'{{order.id}}','{{ product.price }}','price{{ forloop.parentloop.counter }}')" value="{{ order.qty }}" min="1" max="99" style="width: 40px;"> {% endcomment %}
                    {% comment %} <input type="text" readonly value="{{ order.order_date }}"  > {% endcomment %}
                    {{ order.order_date }}
                </td>
                <td><span>&#8377;</span>
                    {% widthratio order.product_id.price 1 order.qty   %}
                    {% comment %} <input type="number" id="price{{ order.id }}" value="{% widthratio order.product_id.price 1 order.qty   %}" min="1" readonly></td> {% endcomment %}
                {% comment %} {% endif %} {% endcomment %}
                	 
            </tr>
            {% endfor %}
                

            </tbody>
        </table>
        
    </div>
</div> 
{% else %}
<h1 class="text-danger" style="position:relative;top:150px;left:620px">No Data Found</h1>
{% endif %}
{% endblock %}