customer/urls.py
from django import views
from django.urls import path
from . import views

app_name='customer'

urlpatterns = [
    path('',views.index,name='index'),
    path('signup',views.signup,name='signup'),
    path('login',views.login,name='login'),
    path('verifyotp', views.verify_otp, name='verify_otp'),
    path('home',views.customer_home,name='cust_home'),
    path('logout',views.cust_logout,name='logout'),
    path('search', views.search_products, name='search'),
    path('product/<int:id>', views.view_product, name='view_product'),
    path('add-to-bag', views.add_to_bag, name="add_to_bag"),
    path('bag', views.view_bag, name="bag"),
    path('update-qty', views.update_quantity, name="update_qty"),
    path('order-product', views.order_product, name='order_product'),
    path('update-payment', views.update_payment, name='update_payment'),
    path('my-orders', views.view_orders, name='my_orders'),
    path('change-passwd', views.change_password, name='change_passwd'),
    path('profile', views.view_profile, name='profile'),
    path('edit-profile', views.update_profile, name='update_profile'),
    path('password-otp', views.send_otp, name='send_otp'),
    path('forgot-passwd', views.forgot_passwd, name='forgot'),
    path('check_avilable/',views.check_avilable,name="check_available")



]

e_commerce/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ecom/',include('customer.urls')),
    path('ecom-admin/',include('ecom_admin.urls')),
    path('reseller/',include('reseller.urls'))
]+static(settings.MEDIA_URL, document_root =  settings.MEDIA_ROOT)

reseller/urls.py
from django import views
from django.urls import path
from . import views

app_name='reseller'

urlpatterns = [

    path('reseller-home',views.reseller_home,name='reseller_home'),
    path('add-product',views.add_product,name='add_product'),
    path('all-products',views.view_products,name='view_products'),
    path('product/<int:id>/',views.edit_product,name='edit_product'),
    path('update-product',views.update_product,name='update_product'),
    path('product-del',views.delete_product,name='del_product'),
    path('orders',views.view_orders,name='orders'),
    path('logout',views.logout,name='logout')


]

reseller/models.py
from datetime import datetime
from django.db import models

# Create your models here.

class Resellers(models.Model):

    cmp_name = models.CharField(max_length=30,db_column='c_name')
    company_regid = models.CharField(max_length=12,db_column='reg_id')
    cmp_addr = models.CharField(max_length=70,db_column='addr')
    country = models.CharField(max_length=30,db_column='cntry')
    cmp_phno = models.CharField(max_length=12,db_column='phno')
    acc_holder = models.CharField(max_length=30,db_column='acc_hld')
    acc_no = models.CharField(max_length=30,db_column='acc_no')
    acc_ifsc = models.CharField(max_length=30,db_column='ifsc')
    user_type = models.CharField(max_length=20,db_column='type')
    email=models.CharField(max_length=30,db_column='email')
    passwd=models.CharField(max_length=30,db_column='passwd')
    user_id = models.IntegerField(db_column='log_id')
    request_date = models.DateField(default=datetime.now)
    status = models.CharField(max_length=20, default= 'inactive')

    class Meta:
        db_table='resellers'


class Products(models.Model):
    title = models.CharField(max_length=30,db_column='title')
    reg_product_id = models.CharField(max_length=12,db_column='p_id')
    desc = models.TextField(db_column='desc')
    img = models.ImageField(upload_to = 'product_images/', blank = True, null = True,db_column='img')
    price = models.IntegerField(db_column='price')
    quantity = models.IntegerField(db_column='qty')
    weight = models.IntegerField(db_column='wt')
    weight_unit = models.CharField(max_length=12,db_column='unit')
    category = models.CharField(max_length=12,db_column='cat')
    subcategory = models.CharField(max_length=12,db_column='sub_cat')
    vendor = models.CharField(max_length=100,db_column='vendor')
    status = models.CharField(max_length=100,db_column='status')
    reseller = models.ForeignKey(Resellers, on_delete=models.CASCADE,db_column='reseller')

    class Meta:
        db_table='products'

reseller/views.py
from itertools import product
from os import stat
import re
from django import http
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from customer.models import Orders

from e_commerce.auth_gaurd import auth_seller
from .models import *

# Create your views here.

@auth_seller
def reseller_home(request):
   
    return render(request,'reseller/home.html')

@auth_seller
def add_product(request):
    if request.method=='POST':

        title = request.POST['title'].lower()
        reg_product_id = request.POST['regproductid']
        description = request.POST['description'].lower()
        img = request.FILES['image']
        price = request.POST['price']
        quantity = request.POST['quantity']
        weight = request.POST['weight']
        weight_unit = request.POST['weightunit']
        category = request.POST['category']
        subcategory = request.POST['subcategory']
        vendor = request.POST['vendor'].lower()
        status = request.POST['status'].lower()
        reseller_id = Resellers.objects.get(id=request.session['s_id'])
        product_exist=Products.objects.filter(reg_product_id=reg_product_id)
        if not product_exist:
            product = Products(title=title, reg_product_id=reg_product_id, desc=description, img=img, price=price, quantity=quantity, weight=weight, weight_unit=weight_unit, category=category, subcategory=subcategory, vendor=vendor, status=status, reseller=reseller_id)
            product.save()
            return JsonResponse({'res':True})
        else:
            return JsonResponse({'res':False})
            
        # product_id = product.pk
        
    return render(request,'reseller/add_product.html')

@auth_seller
def view_products(request):

    products=Products.objects.filter(reseller=request.session['s_id'])
    return render(request,'reseller/all_products.html',{'products':products,})

@auth_seller
def edit_product(request,id):
    
    product=Products.objects.get(id=id)
    return render(request,'reseller/edit_product.html',{'product':product,})

@auth_seller
def update_product(request):
    if request.method == "POST":
        
        product_id = request.POST['id'].strip()
        title = request.POST['title'].strip()
        description = request.POST['description'].strip()
        price = request.POST['price'].strip()
        quantity = request.POST['quantity'].strip()
        status = request.POST['status'].strip()
        print(title,'*************************',len(title))
        Products.objects.filter(id=product_id).update(title=title,desc=description,
        price=price,quantity=quantity,status=status)
        return JsonResponse({'msg':'Update Succesfull'})
        
@auth_seller
def delete_product(request):
    
    get_id= int(request.GET['id'])
    product = Products.objects.get(id=get_id)
    product.delete()
    return JsonResponse({'msg':'Product Deleted'})


def logout(request):
    del request.session['s_id']
    request.session.flush()
    return redirect('customer:login')

def view_orders(request):
    
    order_details=Orders.objects.filter(reseller=request.session['s_id'])
    return render(request,'reseller/orders.html',{'orders':order_details})

reseller/templates/reseller/add_product.html
{% extends "reseller/reseller_master.html" %} {% load static %} {% block reseller_content %}
<script src="{% static 'reseller/scripts/add_product.js' %}"></script>

<div class="py-5 text-left">
    <h2 style="margin-left:390px"  class="text-danger">Add product</h2>
</div>
<div class="row">
    <div class="col-md-8 order-md-1">
        <form class="needs-validation" novalidate enctype="multipart/form-data" id="add_product" style="margin-left:220px" onload="resetSelection();">
            {% csrf_token %}
            <div class="mb-3">
                <label for="title">Title</label>
                <div class="input-group">
                    <input type="text" class="form-control" id="title" placeholder="Title of the product" required>
                    <div class="invalid-feedback">
                        Product title is required.
                    </div>
                </div>
            </div>
            <div class="mb-3">
                <label for="regproductid">Registered product id</label>
                <div class="input-group">
                    <input type="text" class="form-control" id="regproductid" placeholder="Registered product id" required>
                    <div class="invalid-feedback">
                        Registered product id is required.
                    </div>
                </div>
            </div>
            <div class="mb-3">
                <label for="description">Description </label>
                <div class="input-group">
                    <textarea class="form-control" id="description" required></textarea>
                    <div class="invalid-feedback">
                        Please enter a description about the product.
                    </div>
                </div>
            </div>
            <div class="mb-3">
                <label for="customFile">Upload product pictures</label>
                <input type="file" id="customFile" placeholder="choose" class="form-control" required>
                <div class="invalid-feedback">
                    Please upload a picture.
                </div>
            </div>
            <div class="mb-3">
                <label for="price">Price</label>
                <div class="input-group">
                    <input type="number" class="form-control" id="price" placeholder="₹ 0.0" required>
                    <div class="invalid-feedback">
                        Please enter the price.
                    </div>
                </div>
            </div>
            <div class="mb-3">
                <label for="quantity">Quantity</label>
                <div class="input-group">
                    <input type="number" class="form-control" id="quantity" placeholder="Available quantity" required>
                    <div class="invalid-feedback">
                        Please enter the quantity.
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 mb-6">
                    <label for="weight">Weight</label>
                    <div class="input-group">
                        <input type="number" class="form-control" id="weight" placeholder="0.0" required>
                        <div class="invalid-feedback">
                            Please enter the weight of the product.
                        </div>
                    </div>
                </div>
                <div class="col-md-3 mb-3">
                    <label for="weightunit">Weight unit</label>
                    <select class="custom-select d-block w-100 form-control" id="weightunit" required>
                        <option value="">Choose</option>
                        <option>kg</option>
                        <option>g</option>
                        <option>lb</option>
                        <option>oz</option>
                    </select>
                    <div class="invalid-feedback">
                        Please select a unit.
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 mb-6">
                    <label for="category">Category</label>
                    <select class="custom-select d-block w-100" id="category" size="1" onchange="makeSubmenu(this.value);" required>
                        <option value="" disabled selected>Choose</option>
                        <option>Gadgets</option>
                        <option>Clothes</option>
                        <option>Footwear</option>
                        
                        </select>
                    <div class="invalid-feedback">
                        Please select a category.
                    </div>
                </div>
                <div class="col-md-2 mb-3">
                    <label for="subcategory">Sub category</label>
                    <select class="custom-select d-block w-100" id="subcategory" size="1" required>
                        <option value="" disabled selected>Choose</option>
                        <option></option>
                    </select>
                    <div class="invalid-feedback">
                        Please select a sub category.
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 mb-6">
                    <label for="vendor">Brand</label>
                    <div class="input-group">
                        <input type="text" class="form-control" id="brand" placeholder="ex: Nike" required>
                        <div class="invalid-feedback">
                            Please enter the brand name.
                        </div>
                    </div>
                </div>
                <div class="col-md-2 mb-3">
                    <label for="status">Status</label>
                    <select class="custom-select d-block w-100" id="status" required>
                        <option value="">Choose</option>
                        <option>Active</option>
                        <option>Draft</option>
                    </select>
                    <div class="invalid-feedback">
                        Please enter the status.
                    </div>
                </div>
            </div>
            <div class="mb-3">
                <button class="btn btn-primary btn-lg btn-block" type="submit">Save</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

reseller/templates/reseller/all_products.html
{% extends "reseller/reseller_master.html" %} {% load static %} {% block reseller_content %}
<script src="{% static 'reseller/scripts/delete_product.js' %}"></script>
<nav class="navbar navbar-expand-lg navbar-dark bg-light">
    <div class="container">
        <a class="navbar-brand text-dark font-weight-bold" href="#">Products</a>
        <div class="collapse navbar-collapse" id="navbarResponsive">
        </div>
        <a href="{% url 'reseller:add_product' %}" class="btn btn-primary" id="menu-toggle">Add product</a>
    </div>
</nav>
<nav class="navbar navbar-expand-lg navbar-dark bg-light">
    <button class="navbar-toggler bg-dark" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span> </button>
    <div class="collapse navbar-collapse" id="navbarColor02">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link text-dark" href="#">All
                      <span class="sr-only">(current)</span>
                    </a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Status
                    </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item text-dark" href="#">Active</a>
                    <a class="dropdown-item" href="#">Draft</a>
                    <a class="dropdown-item" href="#">Archieved</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" href="#">filter 3</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" href="#">filter 4</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search">
            <button class="btn btn-primary my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>
<div class="row text-center" style="padding-top: 26pt;max-height: 300px;min-height: 300px;">
    {% for product in products %}
    <div class="col-lg-3 col-md-6 mb-4">
        <div >
            <img class="card-img-top" src="{{ product.img.url }}" style="min-height: 250px; max-height: 250px;">
            <div class="card-body">
                <h4 class="card-title">{{product.title|title}}</h4>
                <h6>{{product.quantity}} in stock</h6>
                <h6>Status : {{product.status|capfirst}}</h6>
                <h6>Vendor : {{product.vendor|title}}</h6>
            </div>
            <div class="card-footer">
                <a class="btn btn-primary" id="edit" href="{% url 'reseller:edit_product' product.id %}">Edit</a>
                <button onclick="delete_product('{{ product.id }}')" class="btn btn-danger">Delete</button>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

reseller/templates/reseller/home.html
{% extends "reseller/reseller_master.html" %} {% load static %} {% block reseller_content %}


    <h2 style='position:relative;top:260px;left:390px' class="text-danger">Welcome Home</h2>

{% endblock %}

reseller/templates/reseller/orders.html
{% extends "reseller/reseller_master.html" %} {% block reseller_content %}{% load static %}

<div class="container">
    <div class="row" style="min-height: 300px;">
        {% if orders %}
        <h2 class=mt-2>Your Orders</h2>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Image</th>
                    <th scope="col">Product Name</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Order Date</th>
                    <th scope="col">Total Price</th>
                </tr>
            </thead>
            <tbody>
                {% for order in orders %}
            
                <tr>
                   
                <td><img src="{{order.product_id.img.url }}" alt="" srcset="" height="80px" width="80px"></td>
                <td>{{ order.product_id.title|title }}</td>
                <td>
                    {% comment %} <input type="number" onchange="update_quantity(this,'{{order.id}}','{{ product.price }}','price{{ forloop.parentloop.counter }}')" value="{{ order.qty }}" min="1" max="99" style="width: 40px;"> {% endcomment %}
                    {{order.qty}} No{{order.qty|pluralize}}
                
                </td>
                <td>
                    {% comment %} <input type="number" onchange="update_quantity(this,'{{order.id}}','{{ product.price }}','price{{ forloop.parentloop.counter }}')" value="{{ order.qty }}" min="1" max="99" style="width: 40px;"> {% endcomment %}
                    {% comment %} <input type="text" readonly value="{{ order.order_date }}"  > {% endcomment %}
                    {{ order.order_date }}
                </td>
                <td><span>&#8377; </span>{% widthratio order.product_id.price 1 order.qty   %}</td>
                {% comment %} {% endif %} {% endcomment %}
                	 
            </tr>
            {% endfor %}
                

            </tbody>
        </table>
        {% else %}
                    <h1 class="text-danger" style="margin-left:300px;margin-top:100px">No Orders Yet</h1>
        {% endif %}
    </div>
</div> 

{% endblock %}

reseller/templates/reseller/reseller_master.html
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'reseller/css/master.css' %}">
    <link href="{% static 'reseller/css/add_product.css' %}" rel="stylesheet">

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/checkout/">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
</head>

<body>

    <nav class="theme-color navbar navbar-expand-lg navbar-light border-bottom">
        <button class="btn btn-primary" id="menu-toggle">ALL</button>
        <img src="{% static 'reseller/cs_ecom_logo.png' %}  " alt="img" class="logo-nav">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto mt-2 mt-lg-0 font-weight-bold">
                <li class="nav-item dropdown">
                   
                            <form action="{% url 'reseller:logout' %}" method="POST" >
                                {% csrf_token %}
                                <input type="submit" value="Logout" class="btn btn-danger" name="" id="">
                            </form>
          
                   
                </li>
            </ul>
        </div>
    </nav>

    <div class="d-flex" id="wrapper">
        <!-- Sidebar -->
        <div class="bg-light border-right" id="sidebar-wrapper">
            <div class="theme-color list-group list-group-flush">
                <a href="{% url 'reseller:reseller_home' %}" class="bg-light list-group-item list-group-item-action font-weight-bold" id="home">Home</a>
                <a href="{% url 'reseller:view_products' %}" class="bg-light list-group-item list-group-item-action font-weight-bold" id="products">All Products</a>
                <a href="{% url 'reseller:add_product' %}" class="bg-light list-group-item list-group-item-action font-weight-bold" id="addProduct">Add a product</a>
                <a href="{% url 'reseller:orders' %}" class="bg-light list-group-item list-group-item-action font-weight-bold">View Orders</a>
                <a href="#" class="bg-light list-group-item list-group-item-action font-weight-bold">Option 3</a>
            </div>
        </div>
        <!-- /#sidebar-wrapper -->
        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid" id="content">
                {% block reseller_content %} {% endblock %}
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>


    <script>
        $("#menu-toggle").click(function(e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });
        // // $(document).ready(function(){

        // //         $("#content").load("home");

        // // });
        // // $(document).ready(function(){
        // //     $("#products").click(function(){
        // //         $("#content").load("products");
        // //     });
        // // });
        // // $(document).ready(function(){
        // //     $("#addProduct").click(function(){
        // //         $("#content").load("addProducts");
        // //     });
        // // });
        // // $(document).ready(function(){
        // //     $("#home").click(function(){
        // //         $("#content").load("home");
        // //     });
        // // });
    </script>

    <script>
        // Example starter JavaScript for disabling form submissions if there are invalid fields
    </script>

<footer class="foot text-center text-lg-start" style="background-color: #e0f2f1;">
    <div class="container p-4">
        <div class="row">
            <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
                <h5 class="text-uppercase">Registred office address</h5>
                <p>
                    5th Floor, CAFIT Square, Hilite Business Park, Thondayad Bye-Pass Thondayad, Hilite City, Poovangal, Kozhikode, Kerala 673016
                </p>
            </div>
            <div class="col-lg-2 col-md-4 mb-4 mb-md-0" style="text-align: left;">
                <h5 class="text-uppercase">POLICY</h5>
                <ul class="list-unstyled mb-0">
                    <li><a href="#!" class="text-dark">Return Policy</a></li>
                    <li><a href="#!" class="text-dark">Terms of use</a></li>
                    <li><a href="#!" class="text-dark">Security</a></li>
                    <li><a href="#!" class="text-dark">Privacy</a></li>
                </ul>
            </div>
            <div class="col-lg-2 col-md-4 mb-4 mb-md-0" style="text-align: left;">
                <h5 class="text-uppercase mb-0">About</h5>
                <ul class="list-unstyled">
                    <li><a href="#!" class="text-dark">Contact Us</a></li>
                    <li><a href="#!" class="text-dark">About Us</a></li>
                    <li><a href="#!" class="text-dark">Careers</a></li>
                    <li><a href="#!" class="text-dark">Cybersquare Wholesale</a></li>
                </ul>
            </div>
            <div class="col-lg-2 col-md-4 mb-4 mb-md-0" style="text-align: left;">
                <h5 class="text-uppercase mb-0">Social</h5>
                <ul class="list-unstyled">
                    <li><a href="#!" class="text-dark">Facebook</a></li>
                    <li><a href="#!" class="text-dark">Twitter</a></li>
                    <li><a href="#!" class="text-dark">Youtube</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
        <img src="{% static 'ecom/images/cards.png' %}" class="img-fluid w-25" alt="">
    </div>
</footer>
   
</body>

</html>