customer/urls.py
from django import views
from django.urls import path
from . import views

app_name='customer'

urlpatterns = [
    path('',views.index,name='index'),
    path('signup',views.signup,name='signup'),
    path('login',views.login,name='login'),
    path('verifyotp', views.verify_otp, name='verify_otp'),
    path('home',views.customer_home,name='cust_home'),
    path('logout',views.cust_logout,name='logout'),
    path('search', views.search_products, name='search'),
    path('product/<int:id>', views.view_product, name='view_product'),
    path('add-to-bag', views.add_to_bag, name="add_to_bag"),
    path('bag', views.view_bag, name="bag"),
    path('update-qty', views.update_quantity, name="update_qty"),
    path('order-product', views.order_product, name='order_product'),
    path('update-payment', views.update_payment, name='update_payment'),
    path('my-orders', views.view_orders, name='my_orders'),
    path('change-passwd', views.change_password, name='change_passwd'),
    path('profile', views.view_profile, name='profile'),
    path('edit-profile', views.update_profile, name='update_profile'),
    path('password-otp', views.send_otp, name='send_otp'),
    path('forgot-passwd', views.forgot_passwd, name='forgot'),
    path('check_avilable/',views.check_avilable,name="check_available")



]

e_commerce/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ecom/',include('customer.urls')),
    path('ecom-admin/',include('ecom_admin.urls')),
    path('reseller/',include('reseller.urls'))
]+static(settings.MEDIA_URL, document_root =  settings.MEDIA_ROOT)

ecom_admin/urls.py
from django.urls import path
from . import views

app_name='ecom_admin'

urlpatterns = [
   
    path('admin-home',views.home,name='admin_home'),
    path('reseller-request',views.reseller_request,name='reseller_request'),
    path('view-resellers',views.view_resellers,name='view_resellers')

]

ecom_admin/models.py
from django.db import models

# Create your models here.

ecom_admin/views.py
import imp
from django.shortcuts import render
from reseller.models import Resellers
# Create your views here.

def home(request):
    
    return render(request,'admin_home.html')

def reseller_request(request):
    request_data=Resellers.objects.filter(status='inactive')

    if request.method=='POST':

        rqst=request.POST['req_id']
        reseller=Resellers.objects.get(id=rqst)

        if 'approve' in request.POST:
            reseller.status='active'
            
        if 'reject' in request.POST:
            reseller.status='reject'
        
        reseller.save()
    return render(request,'resellers_request.html',{'request_data':request_data,})


def view_resellers(request):
    resellers=Resellers.objects.filter(status='active')
    print(resellers)
    return render(request,'view_resellers.html',{'resellers':resellers,})

ecom_admin/templates/admin_home.html
{% extends "admin_master.html" %} {% load static %} {% block admin_content %}
<div style="min-height: 400px;">
    <h3 style="margin-left: 200px;margin-top: 60px;">Welcome Admin</h3>
</div>

{% endblock %}

ecom_admin/templates/admin_master.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Admin</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
    <script src="{% static 'reseller/scripts/jquery-3.5.1.min.js' %}"></script>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'admin/css/admin-style.css' %}">
    <link rel="stylesheet" href="{% static 'admin/css/mng_reseller.css' %}">
</head>

<body>
    <div class="wrapper">

        <nav id="sidebar">
            <div class="sidebar-header">
                <img src="{% static 'images/cs_ecom_logo.png' %}" class="img-fluid logo-cybersquare" alt="">
            </div>

            <ul class="list-unstyled components">
                <li>
                    <a href="{% url 'ecom_admin:reseller_request' %}" class="adminnavitem">Pending Approval</a>
                </li>
                <li>
                    <a href="{% url 'ecom_admin:view_resellers' %}" class="adminnavitem">View Resellers</a>
                </li>

                <li>
                    <a href="" class="adminnavitem">Delete Resellers</a>
                </li>

            </ul>


        </nav>

        <div id="content">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">

                    <button type="button" id="sidebarCollapse" class="btn btn-info">
                        <i class="fa fa-bars" aria-hidden="true"></i>
                      
                    </button>

                    <ul class="nav navbar-nav ml-auto">
                        <li class="nav-item active">
                            <div class="btn-group">
                                <span type="button" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Administrator <i class="fa fa-users" aria-hidden="true"></i>
                                </span>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <button class="dropdown-item" type="button">Change Admin name?</button>
                                    <button class="dropdown-item" type="button">Change password?</button>
                                    <button class="dropdown-item" type="button">Log out <i class="fa fa-sign-out" aria-hidden="true"></i></button>
                                </div>
                            </div>
                        </li>

                    </ul>
                </div>
            </nav>
            <div class="container-fluid">
                {% block admin_content %} {% endblock %}
            </div>
            <footer class="foot text-center text-lg-start" style="background-color: #e0f2f1;">
                <div class="container p-4">
                    <div class="row">
                        <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
                            <h5 class="text-uppercase">Registred office address</h5>
                            <p>
                                5th Floor, CAFIT Square, Hilite Business Park, Thondayad Bye-Pass Thondayad, Hilite City, Poovangal, Kozhikode, Kerala 673016
                            </p>
                        </div>
                        <div class="col-lg-2 col-md-4 mb-4 mb-md-0" style="text-align: left;">
                            <h5 class="text-uppercase">POLICY</h5>
                            <ul class="list-unstyled mb-0">
                                <li><a href="#!" class="text-dark">Return Policy</a></li>
                                <li><a href="#!" class="text-dark">Terms of use</a></li>
                                <li><a href="#!" class="text-dark">Security</a></li>
                                <li><a href="#!" class="text-dark">Privacy</a></li>
                            </ul>
                        </div>
                        <div class="col-lg-2 col-md-4 mb-4 mb-md-0" style="text-align: left;">
                            <h5 class="text-uppercase mb-0">About</h5>
                            <ul class="list-unstyled">
                                <li><a href="#!" class="text-dark">Contact Us</a></li>
                                <li><a href="#!" class="text-dark">About Us</a></li>
                                <li><a href="#!" class="text-dark">Careers</a></li>
                                <li><a href="#!" class="text-dark">Cybersquare Wholesale</a></li>
                            </ul>
                        </div>
                        <div class="col-lg-2 col-md-4 mb-4 mb-md-0" style="text-align: left;">
                            <h5 class="text-uppercase mb-0">Social</h5>
                            <ul class="list-unstyled">
                                <li><a href="#!" class="text-dark">Facebook</a></li>
                                <li><a href="#!" class="text-dark">Twitter</a></li>
                                <li><a href="#!" class="text-dark">Youtube</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
                    <img src="{% static 'ecom/images/cards.png' %}" class="img-fluid w-25" alt="">
                </div>
            </footer>
        
        </div>

    </div>

    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <!-- jQuery Custom Scroller CDN -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function() {
            $("#sidebar").mCustomScrollbar({
                theme: "minimal"
            });

            $('#sidebarCollapse').on('click', function() {
                $('#sidebar, #content').toggleClass('active');
                $('.collapse.in').toggleClass('in');
                $('a[aria-expanded=true]').attr('aria-expanded', 'false');
            });
        });
    </script>
</body>

</html>

ecom_admin/templates/resellers_request.html
{% extends "admin_master.html" %} {% load static %} {% block admin_content %}
<div style="min-height: 420px;">
    
    {% if request_data %}
   
    <table class="table table-hover">

        <tr>
            <th>Request Date</th>
            <th>Company Name</th>
            <th>Reg ID</th>
            <th>Address</th>
            <th>Country</th>
            <th>Phone No</th>
            <th>Account Holder</th>
            <th>Account No</th>
            <th>IFSC</th>
            <th></th>
            <th></th>
        </tr>

        {% for data in request_data %}
        <form action="" method="POST">
            {% csrf_token %}
            <tr>
                <td>{{data.request_date}}</td>
                <td>{{data.cmp_name|title}}</td>
                <td>{{data.company_regid}}</td>
                <td>{{data.cmp_addr|capfirst}}</td>
                <td>{{data.country|title}}</td>
                <td>{{data.cmp_phno}}</td>
                <td>{{data.acc_holder}}</td>
                <td>{{data.acc_no}}</td>
                <td>{{data.acc_ifsc}}</td>
                <td><button name="approve" class="btn btn-success">Active</button></td>
                <td><button name="reject" class="btn btn-danger">Reject</button></td>
                <td><input type="hidden" value="{{data.id}}" name="req_id" id=""></td>
            </tr>
        </form>

        {% endfor %}
    </table>

</div>

{% else %}
<h3 style="position: relative;left: 200px;top: 100px;" class="text-danger">No Request</h3>
{% endif %}
{% endblock %}

ecom_admin/templates/view_resellers.html
{% extends "admin_master.html" %} {% load static %} {% block admin_content %}
<div style="min-height: 420px;">
    
    {% if resellers %}
   
    <table class="table table-hover">

        <tr>
            <th>Request Date</th>
            <th>Company Name</th>
            <th>Reg ID</th>
            <th>Address</th>
            <th>Country</th>
            <th>Phone No</th>
            <th>Account Holder</th>
            <th>Account No</th>
            <th>IFSC</th>
            <th></th>
            <th></th>
        </tr>

        {% for reseller in resellers %}

            <tr>
                <td>{{reseller.request_date}}</td>
                <td>{{reseller.cmp_name|title}}</td>
                <td>{{reseller.company_regid}}</td>
                <td>{{reseller.cmp_addr|capfirst}}</td>
                <td>{{reseller.country|title}}</td>
                <td>{{reseller.cmp_phno}}</td>
                <td>{{reseller.acc_holder}}</td>
                <td>{{reseller.acc_no}}</td>
                <td>{{reseller.acc_ifsc}}</td>
                
            </tr>

        {% endfor %}
    </table>

</div>

{% else %}
<h3 style="position: relative;left: 200px;top: 100px;" class="text-danger">No Data</h3>
{% endif %}
{% endblock %}